version: '3.8'

services:
  backend:
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mayba
    ports:
      - 3307:3306
  app:
    build: .
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3000:3000