version: '3.8'

services:
  database:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mayba
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - database
    ports:
      - 3000:3000
    environment:
      - MYSQLDB_HOST=database
      - MYSQLDB_USER=root
      - MYSQLDB_ROOT_PASSWORD=123456
      - MYSQLDB_DATABASE=mayba
      - MYSQLDB_LOCAL_PORT=3307
      - MYSQLDB_DOCKER_PORT=3306
      - JWT_SECRET=mysecretkey
    volumes:
      - .:/app
    command: "npm start"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    links:
      - app

volumes:
  db_data:
